# Generated by Django 4.1.7 on 2023-05-31 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_addpost_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addpost",
            name="likes",
        ),
    ]
