# Generated by Django 4.1.7 on 2023-06-01 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_like"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
