# Generated by Django 4.1.7 on 2023-06-02 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0008_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addpost",
            name="like",
        ),
    ]
