# Generated by Django 4.1.7 on 2023-06-02 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0009_remove_addpost_like"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="Follow",
        ),
    ]
