# Generated by Django 4.1.7 on 2023-06-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0014_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
